const challenges = [
        {
            id: '1', rank: 1,
            name: 'The Hell Challenge',
            difficulty: 'extreme_demon',
            description: '비대칭 듀얼, 좁은 간격의 웨이브, 일자비행, 삼단가시가 맵에 도배되어있는 극악무도한 맵입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123150415',
            views: 4500,
            completions: 3,
            attempts: 2000,
            videoUrl: 'https://www.youtube.com/watch?v=Ed6U_NmhWPk',
            imageUrl: './the_hell_challenge.png'
        },
        {
            id: '2', rank: 2,
            name: 'Chaos Ship',
            difficulty: 'extreme_demon',
            description: '조금만 틀어져도 죽는 매우 좁은 간격의 비행 챌린지입니다.',
            creator: 'ShipMaster',
            verifier: 'ChaosV',
            levelId: '123189789',
            views: 40,
            completions: 0,
            attempts: 0,
            videoUrl: 'https://www.youtube.com/embed/your_chaos_ship_official_video',
            isZre: true,
            zreVideoUrl: 'https://www.youtube.com/watch?v=p3eM8utDvJ8',
            zreImageUrl: './chaos_ship_zre_proof.png',
            imageUrl: './chaos_ship.png'
        },
        {
            id: '3', rank: 3,
            name: 'Relief 2',
            difficulty: 'extreme_demon',
            description: '잦은 변속과 모드전환이 특징인 맵입니다. 몇 안되는 고퀄맵이기도 합니다.',
            creator: 'PlayerX',
            verifier: 'PlayerX',
            levelId: '100556994',
            views: 50,
            completions: 1,
            attempts: 100,
            videoUrl: 'https://www.youtube.com/watch?v=xXKBQAr_nv0',
            imageUrl: './relief_2.png'
        },
        {
            id: '4', rank: 4,
            name: 'Rebition 2',
            difficulty: 'insane_demon',
            description: '유명 익스트림 데몬 The Golden 의 노래를 사용한 웨이브 챌린지 맵입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '72591414',
            views: 2500,
            completions: 15,
            videoUrl: '',
            imageUrl: './rebition_2.png'
        },
        {
            id: '5', rank: 5,
            name: 'Gonna Go',
            difficulty: 'insane_demon',
            description: '즈레 챌린지 리스트의 난이도가 급격하게 오르게 만든 맵입니다. 극칼타로 이루어진 맵이며 프퍼펙이 있는 것이 특징입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '122035043',
            views: 1800,
            completions: 11,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            imageUrl: './gonna_go.png'
        },
        {
            id: '6', rank: 6,
            name: 'NEVADA',
            difficulty: 'insane_demon',
            description: '싱크 기반의 챌린지입니다. 마지막에 투명 상태로 좁은 간격을 지나가야하는 악독한 소고기 유도가 있는 것이 특징입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123872401',
            views: 1200,
            completions: 22,
            videoUrl: 'https://www.youtube.com/watch?v=9roZ0X9GKPk',
            imageUrl: './NVEDA.png'
        },
        {
            id: '7', rank: 7,
            name: 'True Sink',
            difficulty: 'hard_demon',
            description: '싱크 기반의 챌린지입니다. 마지막에 공점 칼타로 1칸 간격을 지나야 하는 것이 특징입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123362423',
            views: 900,
            completions: 35,
            videoUrl: 'https://www.youtube.com/embed/true_sink_video_url',
            imageUrl: './true_sink.png'
        },
        {
            id: '8', rank: 8,
            name: 'AAAAAAAAAAAAAAAAAAAA',
            difficulty: 'hard_demon',
            description: '좁은 간격과 칼타, 타이밍을 잡기 어려운 비행기가 특징인 맵입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '122654332',
            views: 850,
            completions: 45,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            imageUrl: './aaaaaaaaaaa.png'
        },
        {
            id: '9', rank: 9,
            name: 'Persephone',
            difficulty: 'hard_demon',
            description: '극칼타로 이루어진 챌린지입니다. 현재는 업데이트 버전의 등장으로 플레이 할 수 없습니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123358917',
            views: 700,
            completions: 50,
            videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
            imageUrl: './persephone.png'
        },
        {
            id: '10', rank: 10,
            name: 'Speeeeeeeeeeeeeeed',
            difficulty: 'medium_demon',
            description: '극칼타로 이루어진 챌린지입니다. 마지막 삼단가시로 소고기 유도가 있습니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123073199',
            views: 650,
            completions: 70,
            videoUrl: '',
            imageUrl: './speeeeeeeeeeeeeed.png'
        },
        {
            id: '11', rank: 11,
            name: 'Rusttttt',
            difficulty: 'medium_demon',
            description: '약 5초의 매우 짧은 웨이브 챌린지입니다. 짧은 길이를 좁은 간격으로 보완한 챌린지입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123417172',
            views: 550,
            completions: 85,
            videoUrl: '',
            imageUrl: './rusttttt.png'
        },
        {
            id: '12', rank: 12,
            name: 'Buzori',
            difficulty: 'easy_demon',
            description: '대시링을 이용하여 극칼타를 만들어낸 챌린지입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '114207036',
            views: 400,
            completions: 110,
            videoUrl: '',
            imageUrl: './buzori.png'
        },
        {
            id: '13', rank: 13,
            name: 'invincible wave',
            difficulty: 'easy_demon',
            description: '싱크에 맞춰 가감속을 배치해 일명 "꾹꾹이 겜플"을 만들어낸 맵입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '117950820',
            views: 350,
            completions: 130,
            videoUrl: '',
            imageUrl: './invincible_wave.png'
        },
        {
            id: '14', rank: 14,
            name: 'Epilogue',
            difficulty: 'easy_demon',
            description: '싱크 기반의 칼타 챌린지입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '123780214',
            views: 300,
            completions: 150
        },
        {
            id: '15', rank: 15,
            name: 'Yescubed',
            difficulty: 'easy_demon',
            description: '싱크 기반의 웨이브 챌린지입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '115388205',
            views: 280,
            completions: 165
        },
        {
            id: '16', rank: 16,
            name: 'Extreme jump',
            difficulty: 'easy_demon',
            description: '저속 큐브 칼타 챌린지입니다. 후반에 급발진 4배속 웨이브가 있는 것이 특징입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '111094992',
            views: 250,
            completions: 180
        },
        {
            id: '17', rank: 17,
            name: 'JK Chall Rm',
            difficulty: 'easy_demon',
            description: '웨이브 챌린지입니다. 마지막에 D블럭을 이용한 버그성 겜플이 있는 것이 특징입니다.',
            creator: 'ZreGD',
            verifier: 'GDVerifierPro',
            levelId: '117995228',
            views: 220,
            completions: 195
        }
    ].sort((a, b) => a.rank - b.rank);

let upcomingChallenges = [];

export { challenges, upcomingChallenges };
